 /*
 * API version: 0.1.9
 * Generated by: Swagger Codegen 
 */
package main

import (
    sw "github.com/gabrielmb20/gowebservices/go/go"
    "log"
    "net/http"
    "os"
)

func main() {
    log.Printf("Server started")

    router := sw.NewRouter()

    log.Fatal(http.ListenAndServe(":"+os.Getenv("PORT"), router))
}

